usr/share/applications/messaging-app*.desktop
usr/share/url-dispatcher/urls
usr/share/content-hub/peers/messaging-app
usr/share/locale/*/LC_MESSAGES/messaging-app.mo
usr/share/messaging-app/*.qml
usr/share/messaging-app/*.js
usr/share/messaging-app/assets
usr/share/messaging-app/3rd_party
usr/share/messaging-app/AttachmentDelegates/*.qml
usr/share/messaging-app/Dialogs/*.qml
usr/share/messaging-app/Stickers/*.qml
usr/bin/*messaging-app*
debian/usr.bin.messaging-app etc/apparmor.d
